#ifndef C_GROUP_PROJECT_RUNTIME_MODES_H
#define C_GROUP_PROJECT_RUNTIME_MODES_H

    #define MODE_NORMAL 0
    #define MODE_DEBUG 1
    #define MODE_INFO 2

#endif /* C_GROUP_PROJECT_RUNTIME_MODES_H */
